import models from "@models";

type PrismaClientType = typeof models;
const prisma = models as PrismaClientType;

type CreateGenerationRuleInput = {
  questionFormat?: "SINGLE_CHOICE" | "MULTIPLE_CHOICE" | "ESSAY";
  questionTypeId?: string;
  totalCount: number;
  pointsPerQuestion: number;
};

type SubmitAnswerInput = {
  questionId: string;
  answerId?: string;
  essayAnswer?: string;
};

// Fisher-Yates shuffle để random câu hỏi
function shuffle<T>(arr: T[]): T[] {
  const copied = [...arr];
  for (let i = copied.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copied[i], copied[j]] = [copied[j], copied[i]];
  }
  return copied;
}

// Resolve subjectId theo scope của test
async function resolveSubjectIdByTestScope(test: {
  scope: string;
  chapterId: string | null;
  subjectId: string | null;
  courseId: string | null;
}): Promise<string> {
  if (test.scope === "SUBJECT") {
    if (!test.subjectId) throw new Error("Test SUBJECT thiếu subjectId");
    return test.subjectId;
  }

  if (test.scope === "CHAPTER") {
    if (!test.chapterId) throw new Error("Test CHAPTER thiếu chapterId");
    const chapter = await prisma.chapter.findUnique({
      where: { id: test.chapterId },
      select: { subjectId: true },
    });
    if (!chapter) throw new Error("Không tìm thấy chapter của test");
    return chapter.subjectId;
  }

  if (test.scope === "COURSE") {
    if (!test.courseId) throw new Error("Test COURSE thiếu courseId");
    const subject = await prisma.subject.findFirst({
      where: { courseId: test.courseId },
      select: { id: true },
    });
    if (!subject) throw new Error("Không tìm thấy subject thuộc course của test");
    return subject.id;
  }

  throw new Error("Scope không hợp lệ");
}

/**
 * ✅ Tạo bài test (quiz / assignment)
 * Hỗ trợ cả đề gán tay và đề auto-generate theo rule
 */
export async function createTest(
  teacherId: string,
  data: {
    scope: "CHAPTER" | "SUBJECT" | "COURSE";

    chapterId?: string;
    subjectId?: string;
    courseId?: string;

    title: string;
    testType: "QUIZ" | "ESSAY";
    durationMinutes: number;
    startTime?: Date;
    endTime?: Date;
    questionIds?: string[];

    // ✅ bổ sung cho auto-generate
    isAutoGenerated?: boolean;
    generationRules?: CreateGenerationRuleInput[];
  }
) {
  // 🔥 chống gửi nhiều scope
  const scopeCount =
    Number(!!data.chapterId) +
    Number(!!data.subjectId) +
    Number(!!data.courseId);

  if (scopeCount !== 1) {
    throw new Error("Chỉ được chọn 1 scope");
  }

  // ✅ validate scope + quyền
  let subjectId = "";

  if (data.scope === "CHAPTER") {
    if (!data.chapterId) throw new Error("Thiếu chapterId");

    const chapter = await prisma.chapter.findFirst({
      where: {
        id: data.chapterId,
        subject: {
          teachers: { some: { teacherId } },
        },
      },
      select: { subjectId: true },
    });

    if (!chapter) throw new Error("Không có quyền");
    subjectId = chapter.subjectId;
  }

  if (data.scope === "SUBJECT") {
    if (!data.subjectId) throw new Error("Thiếu subjectId");

    const subject = await prisma.subject.findFirst({
      where: {
        id: data.subjectId,
        teachers: { some: { teacherId } },
      },
      select: { id: true },
    });

    if (!subject) throw new Error("Không có quyền");
    subjectId = subject.id;
  }

  if (data.scope === "COURSE") {
    if (!data.courseId) throw new Error("Thiếu courseId");

    const subject = await prisma.subject.findFirst({
      where: {
        courseId: data.courseId,
        teachers: {
          some: { teacherId },
        },
      },
      select: { id: true },
    });

    if (!subject) throw new Error("Không có quyền");
    subjectId = subject.id;
  }

  // build scope field
  const connectData: any = {};
  if (data.scope === "CHAPTER") connectData.chapterId = data.chapterId;
  if (data.scope === "SUBJECT") connectData.subjectId = data.subjectId;
  if (data.scope === "COURSE") connectData.courseId = data.courseId;

  const isAutoGenerated = data.isAutoGenerated ?? false;

  // ✅ Flow gán tay câu hỏi (giữ nguyên)
  if (!isAutoGenerated) {
    if (!data.questionIds || data.questionIds.length === 0) {
      throw new Error("Thiếu questionIds");
    }

    const questions = await prisma.question.findMany({
      where: {
        id: { in: data.questionIds },
        subjectId,
      },
      select: { id: true },
    });

    if (questions.length !== data.questionIds.length) {
      throw new Error("Có câu hỏi không thuộc đúng phạm vi");
    }

    return prisma.test.create({
      data: {
        scope: data.scope,
        ...connectData,
        title: data.title,
        testType: data.testType,
        durationMinutes: data.durationMinutes,
        startTime: data.startTime,
        endTime: data.endTime,
        isAutoGenerated: false,
        testQuestions: {
          create: data.questionIds.map((qId, index) => ({
            questionId: qId,
            points: 1,
            sortOrder: index + 1,
          })),
        },
      },
      include: {
        testQuestions: {
          include: {
            question: { include: { answers: true } },
          },
        },
        generationRules: true,
      },
    });
  }

  // ✅ Flow auto-generate
  const rules = data.generationRules || [];
  if (rules.length === 0) {
    throw new Error("generationRules không được rỗng");
  }

  const allowedFormats = ["SINGLE_CHOICE", "MULTIPLE_CHOICE", "ESSAY"] as const;
  let totalRequested = 0;

  for (const rule of rules) {
    if (rule.questionFormat && !allowedFormats.includes(rule.questionFormat)) {
      throw new Error("questionFormat không hợp lệ");
    }
    if (rule.totalCount <= 0) {
      throw new Error("totalCount phải > 0");
    }
    totalRequested += rule.totalCount;
  }

  if (totalRequested <= 0) {
    throw new Error("Tổng totalCount phải > 0");
  }

  return prisma.test.create({
    data: {
      scope: data.scope,
      ...connectData,
      title: data.title,
      testType: data.testType,
      durationMinutes: data.durationMinutes,
      startTime: data.startTime,
      endTime: data.endTime,
      isAutoGenerated: true,
      generationRules: {
        create: rules.map((rule) => ({
          questionFormat: rule.questionFormat ?? null,
          questionTypeId: rule.questionTypeId ?? null,
          totalCount: rule.totalCount,
          pointsPerQuestion: rule.pointsPerQuestion,
        })),
      },
    },
    include: {
      generationRules: true,
      testQuestions: {
        include: {
          question: { include: { answers: true } },
        },
      },
    },
  });
}

/* ✅ 1.2 List Test */
export async function listTestsByChapter(chapterId: string) {
  return prisma.test.findMany({
    where: {
      chapterId,
      scope: "CHAPTER",
    },
    orderBy: { createdAt: "desc" },
  });
}

export async function listTestsBySubject(subjectId: string) {
  return prisma.test.findMany({
    where: {
      subjectId,
      scope: "SUBJECT",
    },
    orderBy: { createdAt: "desc" },
  });
}

export async function listTestsByCourse(courseId: string) {
  return prisma.test.findMany({
    where: {
      courseId,
      scope: "COURSE",
    },
    orderBy: { createdAt: "desc" },
  });
}

/* ✅ 1.3 Get Test Detail */
export async function getTestDetail(testId: string) {
  return prisma.test.findUnique({
    where: { id: testId },
    include: {
      generationRules: true,
      testQuestions: {
        include: {
          question: {
            include: {
              answers: true,
            },
          },
        },
      },
    },
  });
}

/**
 * ✅ Sinh câu hỏi cho từng sinh viên với đề auto-generate
 */
export async function generateQuestionsForStudent(
  testId: string,
  studentId: string,
  subjectId: string
): Promise<{ questionId: string; points: number; sortOrder: number }[]> {
  // studentId đang truyền vào để mở rộng truy vết/caching về sau
  if (!studentId) throw new Error("Thiếu studentId");

  const test = await prisma.test.findUnique({
    where: { id: testId },
    include: {
      generationRules: true,
    },
  });

  if (!test) throw new Error("Test không tồn tại");
  if (!test.isAutoGenerated) throw new Error("Test không dùng auto generate");

  const selected: { questionId: string; points: number; sortOrder: number }[] = [];
  let sortOrder = 1;

  for (const rule of test.generationRules) {
    const questions = await prisma.question.findMany({
      where: {
        subjectId,
        ...(rule.questionFormat ? { questionFormat: rule.questionFormat } : {}),
        ...(rule.questionTypeId ? { typeId: rule.questionTypeId } : {}),
      },
      select: { id: true },
    });

    if (questions.length < rule.totalCount) {
      throw new Error("Ngân hàng câu hỏi không đủ theo generation rule");
    }

    const shuffled = shuffle(questions);
    const picked = shuffled.slice(0, rule.totalCount);

    for (const q of picked) {
      selected.push({
        questionId: q.id,
        points: rule.pointsPerQuestion,
        sortOrder: sortOrder++,
      });
    }
  }

  return selected;
}

/* ✅ 1.4 Submit bài (hỗ trợ manual + auto-generated) */
export async function submitTest(
  studentId: string,
  data: {
    testId: string;
    classGroupId: string;
    answers: SubmitAnswerInput[];
  }
) {
  const test = await prisma.test.findUnique({
    where: { id: data.testId },
    include: {
      generationRules: true,
      testQuestions: {
        include: {
          question: {
            include: {
              answers: true,
            },
          },
        },
      },
    },
  });

  if (!test) throw new Error("Test không tồn tại");
  if (!["CHAPTER", "SUBJECT", "COURSE"].includes(test.scope)) {
    throw new Error("Test scope không hợp lệ");
  }
  if (test.testType === "ESSAY") {
    throw new Error("Bài tự luận phải nộp qua assignment API");
  }

  // ✅ check student thuộc lớp
  const isStudentInClass = await prisma.classGroupUser.findUnique({
    where: {
      userId_classGroupId: {
        userId: studentId,
        classGroupId: data.classGroupId,
      },
    },
  });
  if (!isStudentInClass) throw new Error("Bạn không thuộc lớp này");

  // ✅ check test thuộc lớp
  let isValid = false;

  if (test.scope === "CHAPTER") {
    isValid = !!(await prisma.classGroup.findFirst({
      where: {
        id: data.classGroupId,
        subject: {
          chapters: {
            some: {
              id: test.chapterId!,
            },
          },
        },
      },
      select: { id: true },
    }));
  }

  if (test.scope === "SUBJECT") {
    isValid = !!(await prisma.classGroup.findFirst({
      where: {
        id: data.classGroupId,
        subjectId: test.subjectId!,
      },
      select: { id: true },
    }));
  }

  if (test.scope === "COURSE") {
    isValid = !!(await prisma.classGroup.findFirst({
      where: {
        id: data.classGroupId,
        subject: {
          courseId: test.courseId!,
        },
      },
      select: { id: true },
    }));
  }

  if (!isValid) throw new Error("Test không thuộc lớp này");

  // ✅ check thời gian
  const now = new Date();
  if (test.startTime && now < test.startTime) throw new Error("Chưa đến giờ làm bài");
  if (test.endTime && now > test.endTime) throw new Error("Đã hết giờ làm bài");

  // ✅ chống làm quá số lần
  const attemptsCount = await prisma.submission.count({
    where: {
      testId: data.testId,
      studentId,
    },
  });
  if (attemptsCount >= test.maxAttempts) {
    throw new Error("Bạn đã hết số lần làm bài");
  }

  // ✅ duplicate answer
  const unique = new Set(data.answers.map((a) => a.questionId));
  if (unique.size !== data.answers.length) {
    throw new Error("Duplicate câu trả lời");
  }

  // ✅ lấy danh sách câu hợp lệ theo loại test
  let expectedQuestions: { questionId: string; points: number; sortOrder: number }[] = [];
  let expectedCount = 0;

  if (!test.isAutoGenerated) {
    expectedQuestions = test.testQuestions.map((q) => ({
      questionId: q.questionId,
      points: q.points,
      sortOrder: q.sortOrder,
    }));
    expectedCount = test.testQuestions.length;
  } else {
    const subjectId = await resolveSubjectIdByTestScope({
      scope: test.scope,
      chapterId: test.chapterId,
      subjectId: test.subjectId,
      courseId: test.courseId,
    });

    expectedQuestions = await generateQuestionsForStudent(test.id, studentId, subjectId);
    expectedCount = test.generationRules.reduce((sum, rule) => sum + rule.totalCount, 0);
  }

  const validQuestionIds = expectedQuestions.map((q) => q.questionId);

  // ✅ check câu hỏi hợp lệ
  for (const ans of data.answers) {
    if (!validQuestionIds.includes(ans.questionId)) {
      throw new Error("Câu hỏi không hợp lệ");
    }
  }

  // ✅ check đủ câu
  if (data.answers.length !== expectedCount) {
    throw new Error("Bạn chưa trả lời đầy đủ câu hỏi");
  }

  // ✅ create submission
  const submission = await prisma.submission.create({
    data: {
      testId: data.testId,
      studentId,
      classGroupId: data.classGroupId,
      userAnswers: {
        create: data.answers.map((a) => ({
          questionId: a.questionId,
          answerId: a.answerId,
          essayAnswer: a.essayAnswer,
          isCorrect: false,
        })),
      },
    },
    include: {
      userAnswers: true,
    },
  });

  return submission;
}

/**
 * ✅ Student bắt đầu làm bài:
 * - test thường: trả detail như cũ
 * - test auto: sinh câu động theo rule, ẩn isCorrect
 */
export async function getTestWithGeneratedQuestions(testId: string, studentId: string) {
  const test = await prisma.test.findUnique({
    where: { id: testId },
    include: {
      generationRules: true,
      testQuestions: {
        include: {
          question: {
            include: { answers: true },
          },
        },
      },
    },
  });

  if (!test) throw new Error("Test không tồn tại");

  // test thường -> trả detail bình thường
  if (!test.isAutoGenerated) {
    return test;
  }

  // auto-generated -> chặn nếu đã có submission
  const existed = await prisma.submission.findFirst({
    where: {
      testId,
      studentId,
    },
    select: { id: true },
  });

  if (existed) throw new Error("Bạn đã làm bài này rồi");

  const subjectId = await resolveSubjectIdByTestScope({
    scope: test.scope,
    chapterId: test.chapterId,
    subjectId: test.subjectId,
    courseId: test.courseId,
  });

  const generated = await generateQuestionsForStudent(test.id, studentId, subjectId);
  const ids = generated.map((g) => g.questionId);

  const questions = await prisma.question.findMany({
    where: { id: { in: ids } },
    include: {
      answers: {
        select: {
          id: true,
          answerText: true,
          orderIndex: true,
        },
      },
      questionType: true,
    },
  });

  const questionMap = new Map(questions.map((q) => [q.id, q]));

  const dynamicQuestions = generated.map((g) => ({
    questionId: g.questionId,
    points: g.points,
    sortOrder: g.sortOrder,
    question: questionMap.get(g.questionId),
  }));

  return {
    ...test,
    testQuestions: dynamicQuestions,
  };
}

/**
 * ✅ Danh sách test cho giáo viên theo môn
 */
export async function getTeacherTestList(teacherId: string, subjectId: string) {
  // kiểm tra giáo viên được phân công môn
  const allowed = await prisma.subject.findFirst({
    where: {
      id: subjectId,
      teachers: {
        some: { teacherId },
      },
    },
    select: { id: true },
  });

  if (!allowed) throw new Error("Không có quyền truy cập môn học");

  const tests = await prisma.test.findMany({
    where: {
      OR: [
        { scope: "SUBJECT", subjectId },
        { scope: "CHAPTER", chapter: { subjectId } },
      ],
    },
    include: {
      chapter: {
        select: { id: true, title: true },
      },
      testQuestions: {
        select: { questionId: true },
      },
      generationRules: true,
      _count: {
        select: { submissions: true },
      },
    },
    orderBy: { createdAt: "desc" },
  });

  return tests.map((test) => {
    const questionCount = test.isAutoGenerated
      ? test.generationRules.reduce((sum, r) => sum + r.totalCount, 0)
      : test.testQuestions.length;

    return {
      id: test.id,
      title: test.title,
      testType: test.testType,
      scope: test.scope,
      isAutoGenerated: test.isAutoGenerated,
      durationMinutes: test.durationMinutes,
      startTime: test.startTime,
      endTime: test.endTime,
      maxAttempts: test.maxAttempts,
      createdAt: test.createdAt,
      submissionCount: test._count.submissions,
      questionCount,
      chapterId: test.chapter?.id || null,
      chapterTitle: test.chapter?.title || null,
      subjectId: test.subjectId || (test.scope === "CHAPTER" ? subjectId : null),
    };
  });
}

/* ✅ 1.5 AUTO CHẤM */
export async function autoGrade(submissionId: string) {
  const submission = await prisma.submission.findUnique({
    where: { id: submissionId },
    include: {
      test: {
        include: {
          testQuestions: {
            include: {
              question: {
                include: {
                  answers: {
                    where: {
                      isCorrect: true,
                    },
                  },
                },
              },
            },
          },
        },
      },
      userAnswers: true,
    },
  });

  if (!submission) throw new Error("Submission không tồn tại");

  let score = 0;
  const total = submission.userAnswers.length;

  for (const ans of submission.userAnswers) {
    const question = submission.test.testQuestions.find(
      (q) => q.questionId === ans.questionId
    )?.question;

    const correct = question?.answers.find((a) => a.isCorrect);

    if (correct?.id === ans.answerId) {
      await prisma.userQuestionAnswer.update({
        where: { id: ans.id },
        data: { isCorrect: true },
      });
      score++;
    }
  }

  const finalScore = total === 0 ? 0 : (score / total) * 10;

  return prisma.submission.update({
    where: { id: submissionId },
    data: {
      score: finalScore,
      status: "GRADED",
      finalScoreStatus: "AUTO_GRADED",
    },
  });
}
